models/user.py
import datetime as dt
from flask_login import UserMixin
from pr_hillary.extensions import db, bcrypt
from pr_hillary.database import (
    Column,
    Model,
    ReferenceCol,
    relationship,
    SurrogatePK,
)



class User(UserMixin, SurrogatePK, Model):

    __tablename__ = 'users'
    username = Column(db.String(80), unique=True, nullable=False)
    email = Column(db.String(80), unique=True, nullable=False)
    #: The hashed password
    password = Column(db.String(128), nullable=True)
    created_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    first_name = Column(db.String(30), nullable=True)
    last_name = Column(db.String(30), nullable=True)
    active = Column(db.Boolean(), default=False)
    is_admin = Column(db.Boolean(), default=False)

    def __init__(self, username, email, password=None, **kwargs):
        db.Model.__init__(self, username=username, email=email, **kwargs)
        if password:
            self.set_password(password)
        else:
            self.password = None

    def set_password(self, password):
        self.password = bcrypt.generate_password_hash(password)

    def check_password(self, value):
        return bcrypt.check_password_hash(self.password, value)

    @property
    def full_name(self):
        return "{0} {1}".format(self.first_name, self.last_name)

    def __repr__(self):
        return '<User({username!r})>'.format(username=self.username)

forms/user.py
# -*- coding: utf-8 -*-
from flask_wtf import Form
from wtforms import TextField, PasswordField, StringField
from wtforms.validators import DataRequired, Email, EqualTo, Length

from pr_hillary.models.user import User


class RegisterForm(Form):
    username = TextField('Username', validators=[DataRequired(), Length(min=3, max=25)])
    first_name = TextField('first_name', validators=[DataRequired(), Length(min=3, max=25)])
    last_name = TextField('last_name', validators=[DataRequired(), Length(min=3, max=25)])
    email = TextField('Email', validators=[DataRequired(), Email(), Length(min=6, max=40)])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=6, max=40)])
    confirm = PasswordField('Verify password', [DataRequired(), EqualTo('password', message='Passwords must match')])

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append("Username already registered")
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append("Email already registered")
            return False
        return True

class EmailForm(Form):
    email = StringField('Email', validators=[DataRequired(), Email()])


class PasswordForm(Form):
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField('Confirm Password',
                              validators=[DataRequired(), EqualTo('password', message='Passwords must match')])


class UsernameForm(Form):
    username = StringField('Username', validators=[DataRequired()])
    username2 = StringField('Confirm Username',
                            validators=[DataRequired(), EqualTo('username', message='Usernames must match')])

views/user.py
# -*- coding: utf-8 -*-
from flask import (Blueprint, request, render_template, flash, url_for, send_from_directory, make_response,
                   redirect, current_app)

from flask_login import login_required, logout_user, current_user
from pr_hillary.utils import flash_errors, render_extensions
from pr_hillary.forms.user import PasswordForm, EmailForm, UsernameForm
from pr_hillary.extensions import mail
from pr_hillary.models.user import User
from flask_mail import Message
from itsdangerous import URLSafeTimedSerializer


blueprint = Blueprint("user", __name__, url_prefix='/users',
                      static_folder="../static")


@blueprint.route("/")
@login_required
def profile():
    return render_extensions("users/profile.html")

@blueprint.route('/reset', methods=["GET", "POST"])
def reset():
    form = EmailForm()
    if form.validate_on_submit():
        emailuser = User.query.filter_by(email=form.email.data).first_or_404()

        subject = "Password reset requested"
        from pr_hillary.settings import Config

        ts = URLSafeTimedSerializer(Config.SECRET_KEY)
        token = ts.dumps(emailuser.email, salt='recover-key')

        recover_url = url_for('user.reset_with_token', token=token, _external=True)
        html = render_template('email/recover.html', recover_url=recover_url)

        msg = Message(html=html, recipients=[emailuser.email], subject=subject)
        mail.send(msg)

        return redirect(url_for('public.home'))
    else:
        flash_errors(form)

    return render_extensions('users/reset.html', resetform=form)

@blueprint.route('/reset/<token>', methods=["GET", "POST"])
def reset_with_token(token):
    try:
        from pr_hillary.settings import Config

        ts = URLSafeTimedSerializer(Config.SECRET_KEY)
        email = ts.loads(token, salt="recover-key", max_age=86400)
    except:
        return render_template("404.html")

    form = PasswordForm()

    if form.validate_on_submit():
        emailuser = User.query.filter_by(email=email).first_or_404()
        emailuser.set_password(form.password.data)
        emailuser.save()
        return redirect(url_for('public.home'))
    else:
        flash_errors(form)

    return render_extensions('users/reset_with_token.html', resetform=form, token=token)


@blueprint.route('/change_password', methods=['GET', 'POST'])
@login_required
def change_password():
    form = PasswordForm()
    if form.validate_on_submit():
        current_user.set_password(form.password.data)
        current_user.save()
        return redirect(url_for('user.profile'))
    else:
        flash_errors(form)

    return render_extensions('users/change_password.html', resetform=form)


@blueprint.route('/change_username', methods=['GET', 'POST'])
@login_required
def change_username():
    form = UsernameForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.save()
        return redirect(url_for('user.profile'))
    else:
        flash_errors(form)

    return render_extensions('users/change_username.html', resetform=form)

@blueprint.route('/unsubscribe')
@login_required
def unsubscribe():
    return render_extensions('users/unsubscribe.html')


@blueprint.route('/unsubscribe_confirm')
@login_required
def unsubscribe_confirm():
    user = current_user
    user.username = '%s (Unsubscribed)' % (user.username,)
    user.email = '%s (Unsubscribed)' % (user.email,)
    user.is_admin = False
    user.active = False
    user.save()
    logout_user()
    return redirect(url_for('public.home'))

templates/users/change_password.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
  <h3>Change Password</h3>
  <p>Use the form below to change your password.</p>
    <div class="col-lg-4">
    <form action="{{ url_for('user.change_password') }}" method="POST">
    <div class="form-group">
        {{resetform.password.label}}
        {{resetform.password(placeholder="", class_="form-control")}}
    </div>
    <div class="form-group">
        {{resetform.password2.label}}
        {{resetform.password2(placeholder="", class_="form-control")}}
    </div>
    <br>
    <br>
    {{ resetform.csrf_token }}
    <input class="btn btn-default btn-submit" type="submit" value="Change my password" />
    </form>
    </div>
    </div>
{% endblock %}

templates/users/change_username.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
  <h3>Change Username</h3>
  <p>Use the form below to change your username.</p>
    <div class="col-lg-4">
    <form action="{{ url_for('user.change_username') }}" method="POST">
    <div class="form-group">
        {{resetform.username.label}}
        {{resetform.username(placeholder="", class_="form-control")}}
    </div>
    <div class="form-group">
        {{resetform.username2.label}}
        {{resetform.username2(placeholder="", class_="form-control")}}
    </div>
    <br>
    <br>
    {{ resetform.csrf_token }}
    <input class="btn btn-default btn-submit" type="submit" value="Change my username" />
</form>
    </div>
</div>
{% endblock %}

templates/users/profile.html
{% extends "layout.html" %}
{% block content %}
    <h1>Welcome {{ session.username }}</h1>
    <h3>This is the members-only page.</h3>
{% endblock %}

templates/users/reset.html
{% extends "layout.html" %}
{% block content %}
    <div class="col-lg-4">
<form action="{{ url_for('user.reset', token=token) }}" method="POST">
    <div class="form-group">
        {{resetform.email.label}}
        {{resetform.email(placeholder="", class_="form-control")}}
    </div>
    {{ resetform.csrf_token }}
<br>
    <input class="btn btn-default btn-submit" type="submit" value="Send Email" />
</form>
    </div>
{% endblock %}

templates/users/reset_with_token.html
{% extends "layout.html" %}
{% block content %}
    <div class="col-lg-4">
<form action="{{ url_for('user.reset_with_token', token=token) }}" method="POST">
    <div class="form-group">
        {{resetform.password.label}}
        {{resetform.password(placeholder="", class_="form-control")}}
    </div>
    <div class="form-group">
        {{resetform.password2.label}}
        {{resetform.password2(placeholder="", class_="form-control")}}
    </div>
    <br>
    <br>
    {{ resetform.csrf_token }}
    <input class="btn btn-default btn-submit" type="submit" value="Change my password" />
</form>
    </div>
{% endblock %}

templates/users/unsubscribe.html
{% extends "layout.html" %}
{% block content %}
    <div class="col-lg-4">
        <h3>Unsubscribe</h3>
        <p>We hope you don't really want to unsubscribe from {{ cookiecutter.app_name }}, but if you insist, click below.</p>
         <a href="{{ url_for('user.unsubscribe_confirm') }}" class="btn btn-default btn-submit" onclick="return confirm('Are you sure?')">Unsubscribe</a>
    </div>
{% endblock %}